apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: mesh-gateway
  namespace: openshift-ingress
spec:
  gatewayClassName: openshift-default
  listeners:
  - name: http
    hostname: DOMAIN_PLACEHOLDER
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All

