apiVersion: sailoperator.io/v1
kind: Istio
metadata:
  name: default
  namespace: istio-system
spec:
  namespace: istio-system
  updateStrategy:
    type: InPlace
  values:
    meshConfig:
      discoverySelectors:
      - matchLabels:
          istio-discovery: default
      outboundTrafficPolicy:
        mode: REGISTRY_ONLY
